version: 1
snapshot:
  widths: [450, 1050] # px
  enable-javascript: true
  percy-css: |
    div.embed,
    iframe,
    video,
    img[src$=".gif"],
    div#meta-hits {
      display: none !important;  /* don't worry about third-party content/embeds */
    }
    code,
    div.highlight {
      border: 0 !important;  /* no clue why this bugs out... */
    }
    .wave,
    .beat {
      animation: none;
    }
static-snapshots:
  path: public/
  snapshot-files: 'index.html,uses/index.html,notes/{netlify-analytics-review,shodan-search-queries,dropping-dropbox,coronavirus-open-source}/index.html'
agent:
  asset-discovery:
    network-idle-timeout: 2000 # ms
