version: 1
snapshot:
  widths: [450, 1050] # px
  enable-javascript: true
  percy-css: |
    div.embed, iframe, video {
      display: none;
    }
    .wave, .beat {
      animation: none;
    }
static-snapshots:
  path: public/
  snapshot-files: '**/index.html'
  ignore-files: '**/license/*.html,**/privacy/*.html,**/stats/*.html,**/leo/*.html,**/birthday/*.html,**/hillary/*.html'
agent:
  asset-discovery:
    network-idle-timeout: 2000 # ms
