version: 1
snapshot:
  widths: [450, 1050] # px
  enable-javascript: true
  percy-css: |
    div.embed,
    iframe,
    video,
    img[src$=".gif"],
    div#meta-hits {
      display: none !important;  /* don't worry about third-party content/embeds */
    }
    code,
    div.highlight {
      border: 0 !important;  /* no clue why this bugs out... */
    }
    *,
    ::before,
    ::after {
      animation: none !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
static-snapshots:
  path: public/
  snapshot-files: 'index.html,uses/index.html,notes/{how-to-pull-request-fork-github,shodan-search-queries}/index.html'
agent:
  asset-discovery:
    network-idle-timeout: 2000 # ms
