version: 2
snapshot:
  widths:
    - 450
    - 1050
  enable-javascript: true
  percy-css: >
    div.embed,
    iframe,
    video,
    img[src$=".gif"],
    div#meta-hits {
      display: none !important;
    }

    *,
    ::before,
    ::after {
      animation: none !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
static:
  files:
    - "index.html"
    - "uses/index.html"
    - "notes/{how-to-pull-request-fork-github,shodan-search-queries}/index.html"
discovery:
  network-idle-timeout: 750
  disable-cache: true
