version: 1
snapshot:
  widths: [375, 1280] # px
  enable-javascript: true
  percy-css: |
    video {
      display: none;
    }
    div.embed {
      display: none;
    }
    div.highlight {
      border: 0 !important;  /* no clue why this bugs out... */
    }
    .wave, .beat {
      animation: none !important;
    }
static-snapshots:
  path: public/
  snapshot-files: '**/index.html'
agent:
  asset-discovery:
    network-idle-timeout: 10000 # ms
