version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "dependencies"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
